name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        java: [ '11', '17' ]
        os: [ 'ubuntu-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: print Maven and Java versions
      run: mvn --version
    - name: Build
      run: mvn -ntp -B clean verify
    - name: Generate site
      run: mvn -ntp -B clean site -P publicsite
